apiVersion: 1

deleteContactPoints:
  - orgId: 1
    uid: sms-via-twilio-webhook

contactPoints:
  - orgId: 1
    name: Alert webhook
    receivers:
      - uid: alert-webhook
        type: webhook
        settings:
          url: http://sms-notifier:8090/grafana-alert
          httpMethod: POST
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: Alert webhook
    group_by:
      - grafana_folder
      - alertname
